title: Nicotine+
logo: /files/org.nicotine_plus.Nicotine.svg
description: A graphical client for Soulseek
url: https://nicotine-plus.github.io/nicotine-plus/

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - files/README
  - files/windows/README
  - img/README
  - plugins/README

theme: jekyll-theme-minimal
