title: Nicotine+
logo: /files/org.nicotine_plus.Nicotine.svg
description: A graphical client for Soulseek

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - files/README
  - img/README
  - plugins/README

theme: jekyll-theme-minimal
