name: Continuous Integration (DEP-8)

on: [push, pull_request]

jobs:

  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install autopkgtest dependencies
        run: |
          sudo apt update
          sudo apt -y install autopkgtest

      - name: Run autopkgtest
        run: |
          set +e

          if command -v autopkgtest &> /dev/null; then
            sudo autopkgtest . -- null
          else
            # Ubuntu 16.04 uses adt-run
            sudo adt-run --unbuilt-tree . --- null
          fi

          # autopkgtest exit code 2 signifies skipped tests
          if [ $? -gt 2 ]; then
            exit 1
          fi
