name: Nicotine+ CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        python: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        sudo apt-get install libgeoip-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 nicotine pynicotine plugins --ignore=E402,E501,W503,W504
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pip install pytest
        pytest

  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install devscripts debhelper dh-python python-all \
          python-gobject-2 python-setuptools quilt
    - name: Build binary .deb
      run: |
        dpkg-buildpackage -b -rfakeroot -us -uc
    - name: Build source .deb
      run: |
        cd ..
        tar --exclude-vcs -jcf nicotine_1.4.3.orig.tar.bz2 nicotine-plus
        cd nicotine-plus
        dpkg-buildpackage -S -rfakeroot -us -uc
    - name: Collect source .deb artifacts
      run: |
        mkdir ../output
        mv ../nicotine_?.?.?* ../output
    - name: Archive source .deb artifacts
      uses: actions/upload-artifact@v1
      with:
        name: nicotine-debuild-artifacts
        path: ../output